import { createHash } from "node:crypto"

export type Migration = { readonly id: string; readonly sql: string }

const schemaSql = `
CREATE TABLE blobs (sha256 TEXT PRIMARY KEY CHECK(length(sha256)=64 AND sha256 GLOB '[0-9a-f]*' AND sha256 NOT GLOB '*[^0-9a-f]*'), byte_size INTEGER NOT NULL CHECK(byte_size>=0), media_type TEXT NOT NULL, created_at TEXT NOT NULL);
CREATE TABLE documents (id TEXT PRIMARY KEY, kind TEXT NOT NULL CHECK(kind IN ('resume','portfolio','cover_letter','supporting')), title TEXT NOT NULL, state TEXT NOT NULL CHECK(state IN ('active','archived','deleted')) DEFAULT 'active', current_version_id TEXT REFERENCES document_versions(id) ON DELETE RESTRICT, created_at TEXT NOT NULL, archived_at TEXT, deleted_at TEXT);
CREATE TABLE document_versions (id TEXT PRIMARY KEY, document_id TEXT NOT NULL REFERENCES documents(id) ON DELETE RESTRICT, version_number INTEGER NOT NULL CHECK(version_number>0), blob_hash TEXT NOT NULL REFERENCES blobs(sha256) ON DELETE RESTRICT, created_at TEXT NOT NULL, UNIQUE(document_id,version_number));
CREATE TABLE job_posts (id TEXT PRIMARY KEY, title TEXT NOT NULL, company_name TEXT NOT NULL, state TEXT NOT NULL CHECK(state IN ('active','archived','deleted')) DEFAULT 'active', canonical_url TEXT UNIQUE, current_version_id TEXT REFERENCES job_post_versions(id) ON DELETE RESTRICT, created_at TEXT NOT NULL, archived_at TEXT, deleted_at TEXT);
CREATE TABLE job_post_versions (id TEXT PRIMARY KEY, job_post_id TEXT NOT NULL REFERENCES job_posts(id) ON DELETE RESTRICT, version_number INTEGER NOT NULL CHECK(version_number>0), source_kind TEXT NOT NULL CHECK(source_kind IN ('manual','file','url')), body_blob_hash TEXT REFERENCES blobs(sha256) ON DELETE RESTRICT, structured_content TEXT NOT NULL CHECK(json_valid(structured_content)), created_at TEXT NOT NULL, UNIQUE(job_post_id,version_number));
CREATE TABLE applications (id TEXT PRIMARY KEY, job_post_id TEXT REFERENCES job_posts(id) ON DELETE SET NULL, status TEXT NOT NULL CHECK(status IN ('saved','applied','interviewing','offered','rejected','withdrawn')), idempotency_key TEXT UNIQUE, created_at TEXT NOT NULL, archived_at TEXT);
CREATE TABLE application_events (id TEXT PRIMARY KEY, application_id TEXT NOT NULL REFERENCES applications(id) ON DELETE RESTRICT, sequence INTEGER NOT NULL CHECK(sequence>0), event_kind TEXT NOT NULL, payload TEXT NOT NULL CHECK(json_valid(payload)), created_at TEXT NOT NULL, UNIQUE(application_id,sequence));
CREATE INDEX document_versions_document_idx ON document_versions(document_id,version_number DESC);
CREATE INDEX job_post_versions_post_idx ON job_post_versions(job_post_id,version_number DESC);
CREATE INDEX application_events_application_idx ON application_events(application_id,sequence);
CREATE TRIGGER documents_current_version_parent_insert BEFORE INSERT ON documents WHEN NEW.current_version_id IS NOT NULL AND NOT EXISTS (SELECT 1 FROM document_versions WHERE id=NEW.current_version_id AND document_id=NEW.id) BEGIN SELECT RAISE(ABORT,'document version parent mismatch'); END;
CREATE TRIGGER documents_current_version_parent BEFORE UPDATE OF current_version_id ON documents WHEN NEW.current_version_id IS NOT NULL AND NOT EXISTS (SELECT 1 FROM document_versions WHERE id=NEW.current_version_id AND document_id=NEW.id) BEGIN SELECT RAISE(ABORT,'document version parent mismatch'); END;
CREATE TRIGGER job_posts_current_version_parent_insert BEFORE INSERT ON job_posts WHEN NEW.current_version_id IS NOT NULL AND NOT EXISTS (SELECT 1 FROM job_post_versions WHERE id=NEW.current_version_id AND job_post_id=NEW.id) BEGIN SELECT RAISE(ABORT,'job post version parent mismatch'); END;
CREATE TRIGGER job_posts_current_version_parent BEFORE UPDATE OF current_version_id ON job_posts WHEN NEW.current_version_id IS NOT NULL AND NOT EXISTS (SELECT 1 FROM job_post_versions WHERE id=NEW.current_version_id AND job_post_id=NEW.id) BEGIN SELECT RAISE(ABORT,'job post version parent mismatch'); END;
`

const provenanceSql = `
CREATE TABLE provider_runs (id TEXT PRIMARY KEY, provider_kind TEXT NOT NULL, status TEXT NOT NULL CHECK(status IN ('queued','running','succeeded','failed','cancelled')), request_hash TEXT NOT NULL UNIQUE CHECK(length(request_hash)=64 AND request_hash GLOB '[0-9a-f]*' AND request_hash NOT GLOB '*[^0-9a-f]*'), usage_json TEXT NOT NULL CHECK(json_valid(usage_json)), created_at TEXT NOT NULL, completed_at TEXT);
CREATE TABLE artifacts (id TEXT PRIMARY KEY, artifact_type TEXT NOT NULL CHECK(artifact_type IN ('cover_letter','resume','interview_brief','application_answer')), state TEXT NOT NULL CHECK(state IN ('draft','archived','deleted')), provider_run_id TEXT REFERENCES provider_runs(id) ON DELETE SET NULL, body_blob_hash TEXT REFERENCES blobs(sha256) ON DELETE RESTRICT, structured_output TEXT NOT NULL CHECK(json_valid(structured_output)), version_number INTEGER NOT NULL CHECK(version_number>0), created_at TEXT NOT NULL, archived_at TEXT, deleted_at TEXT, UNIQUE(artifact_type,version_number));
CREATE TABLE artifact_inputs (artifact_id TEXT NOT NULL REFERENCES artifacts(id) ON DELETE RESTRICT, input_kind TEXT NOT NULL CHECK(input_kind IN ('document_version','job_post_version','research_record','source_hash')), document_version_id TEXT REFERENCES document_versions(id) ON DELETE RESTRICT, job_post_version_id TEXT REFERENCES job_post_versions(id) ON DELETE RESTRICT, research_record_id TEXT REFERENCES research_records(id) ON DELETE RESTRICT, source_hash TEXT CHECK(source_hash IS NULL OR (length(source_hash)=64 AND source_hash GLOB '[0-9a-f]*' AND source_hash NOT GLOB '*[^0-9a-f]*')), created_at TEXT NOT NULL, PRIMARY KEY(artifact_id,input_kind), CHECK((input_kind='document_version' AND document_version_id IS NOT NULL AND job_post_version_id IS NULL AND research_record_id IS NULL AND source_hash IS NULL) OR (input_kind='job_post_version' AND document_version_id IS NULL AND job_post_version_id IS NOT NULL AND research_record_id IS NULL AND source_hash IS NULL) OR (input_kind='research_record' AND document_version_id IS NULL AND job_post_version_id IS NULL AND research_record_id IS NOT NULL AND source_hash IS NULL) OR (input_kind='source_hash' AND document_version_id IS NULL AND job_post_version_id IS NULL AND research_record_id IS NULL AND source_hash IS NOT NULL)));
CREATE TABLE research_records (id TEXT PRIMARY KEY, job_post_id TEXT REFERENCES job_posts(id) ON DELETE SET NULL, kind TEXT NOT NULL CHECK(length(trim(kind))>0), status TEXT NOT NULL CHECK(status IN ('active','stale','archived')), content_blob_hash TEXT REFERENCES blobs(sha256) ON DELETE RESTRICT, created_at TEXT NOT NULL, archived_at TEXT);
CREATE TABLE research_sources (id TEXT PRIMARY KEY, research_record_id TEXT NOT NULL REFERENCES research_records(id) ON DELETE RESTRICT, canonical_url TEXT NOT NULL CHECK(canonical_url GLOB 'http://*' OR canonical_url GLOB 'https://*'), title TEXT NOT NULL CHECK(length(trim(title))>0), content_hash TEXT NOT NULL CHECK(length(content_hash)=64 AND content_hash GLOB '[0-9a-f]*' AND content_hash NOT GLOB '*[^0-9a-f]*'), excerpt TEXT NOT NULL, status TEXT NOT NULL CHECK(status IN ('available','failed','archived')), body_blob_hash TEXT REFERENCES blobs(sha256) ON DELETE RESTRICT, retrieved_at TEXT NOT NULL, UNIQUE(research_record_id,canonical_url));
CREATE TABLE conversations (id TEXT PRIMARY KEY, application_id TEXT REFERENCES applications(id) ON DELETE SET NULL, title TEXT NOT NULL, created_at TEXT NOT NULL, archived_at TEXT);
CREATE TABLE messages (id TEXT PRIMARY KEY, conversation_id TEXT NOT NULL REFERENCES conversations(id) ON DELETE RESTRICT, sequence INTEGER NOT NULL CHECK(sequence>0), role TEXT NOT NULL CHECK(role IN ('system','user','assistant','tool')), body TEXT NOT NULL CHECK(json_valid(body)), body_blob_hash TEXT REFERENCES blobs(sha256) ON DELETE RESTRICT, provider_run_id TEXT REFERENCES provider_runs(id) ON DELETE SET NULL, created_at TEXT NOT NULL, UNIQUE(conversation_id,sequence));
CREATE INDEX artifacts_provider_run_idx ON artifacts(provider_run_id,created_at DESC);
CREATE INDEX research_sources_record_idx ON research_sources(research_record_id,retrieved_at DESC);
CREATE INDEX messages_conversation_idx ON messages(conversation_id,sequence);
`

const executionSql = `
CREATE TABLE durable_jobs (id TEXT PRIMARY KEY, kind TEXT NOT NULL CHECK(length(trim(kind))>0), state TEXT NOT NULL CHECK(state IN ('queued','leased','running','succeeded','failed','cancelled')), idempotency_key TEXT NOT NULL UNIQUE, payload_json TEXT NOT NULL CHECK(json_valid(payload_json)), lease_owner TEXT, lease_expires_at TEXT, error_code TEXT CHECK(error_code IS NULL OR (length(error_code)>0 AND error_code GLOB '[a-z0-9_]*' AND error_code NOT GLOB '*[^a-z0-9_]*')), error_message TEXT CHECK(error_message IS NULL OR (length(error_message)>0 AND length(error_message)<=1024)), created_at TEXT NOT NULL, updated_at TEXT NOT NULL, CHECK((state IN ('leased','running') AND lease_owner IS NOT NULL AND lease_expires_at IS NOT NULL AND error_code IS NULL AND error_message IS NULL) OR (state='failed' AND lease_owner IS NULL AND lease_expires_at IS NULL AND error_code IS NOT NULL AND error_message IS NOT NULL) OR (state IN ('queued','succeeded','cancelled') AND lease_owner IS NULL AND lease_expires_at IS NULL AND error_code IS NULL AND error_message IS NULL)));
CREATE TABLE durable_job_events (id TEXT PRIMARY KEY, job_id TEXT NOT NULL REFERENCES durable_jobs(id) ON DELETE RESTRICT, sequence INTEGER NOT NULL CHECK(sequence>0), event_kind TEXT NOT NULL, payload_json TEXT NOT NULL CHECK(json_valid(payload_json)), created_at TEXT NOT NULL, UNIQUE(job_id,sequence));
CREATE TABLE provider_settings (provider_kind TEXT PRIMARY KEY, selected_model TEXT, enabled INTEGER NOT NULL CHECK(enabled IN (0,1)), capability_json TEXT NOT NULL CHECK(json_valid(capability_json)), updated_at TEXT NOT NULL);
CREATE TABLE outbound_disclosures (id TEXT PRIMARY KEY, request_hash TEXT NOT NULL UNIQUE CHECK(length(request_hash)=64 AND request_hash GLOB '[0-9a-f]*' AND request_hash NOT GLOB '*[^0-9a-f]*'), provider_kind TEXT NOT NULL REFERENCES provider_settings(provider_kind) ON DELETE RESTRICT, destination TEXT NOT NULL CHECK(destination GLOB 'http://*' OR destination GLOB 'https://*'), action TEXT NOT NULL CHECK(length(trim(action))>0), action_at TEXT NOT NULL, selected_input_hashes TEXT NOT NULL CHECK(json_valid(selected_input_hashes) AND json_type(selected_input_hashes)='array'));
CREATE TABLE runner_registrations (id TEXT PRIMARY KEY, runner_name TEXT NOT NULL UNIQUE CHECK(length(trim(runner_name))>0), token_hash TEXT NOT NULL UNIQUE CHECK(length(token_hash)=64 AND token_hash GLOB '[0-9a-f]*' AND token_hash NOT GLOB '*[^0-9a-f]*'), capability_json TEXT NOT NULL CHECK(json_valid(capability_json)), status TEXT NOT NULL CHECK(status IN ('active','revoked')), registered_at TEXT NOT NULL, last_seen_at TEXT NOT NULL, revoked_at TEXT, CHECK((status='active' AND revoked_at IS NULL) OR (status='revoked' AND revoked_at IS NOT NULL)));
CREATE INDEX durable_jobs_state_idx ON durable_jobs(state,created_at);
CREATE INDEX durable_job_events_job_idx ON durable_job_events(job_id,sequence);
CREATE INDEX disclosures_provider_action_idx ON outbound_disclosures(provider_kind,action_at DESC);
CREATE INDEX runner_registrations_status_idx ON runner_registrations(status,last_seen_at DESC);
CREATE TRIGGER outbound_disclosures_input_hashes_insert BEFORE INSERT ON outbound_disclosures WHEN EXISTS (SELECT 1 FROM json_each(NEW.selected_input_hashes) WHERE json_each.type!='text' OR length(json_each.value)!=64 OR json_each.value GLOB '*[^0-9a-f]*') BEGIN SELECT RAISE(ABORT,'disclosure input hash invalid'); END;
CREATE TRIGGER outbound_disclosures_input_hashes_update BEFORE UPDATE OF selected_input_hashes ON outbound_disclosures WHEN EXISTS (SELECT 1 FROM json_each(NEW.selected_input_hashes) WHERE json_each.type!='text' OR length(json_each.value)!=64 OR json_each.value GLOB '*[^0-9a-f]*') BEGIN SELECT RAISE(ABORT,'disclosure input hash invalid'); END;
CREATE TRIGGER outbound_disclosures_input_hashes_nonempty_insert BEFORE INSERT ON outbound_disclosures WHEN json_array_length(NEW.selected_input_hashes)=0 OR EXISTS (SELECT value FROM json_each(NEW.selected_input_hashes) GROUP BY value HAVING count(*)>1) BEGIN SELECT RAISE(ABORT,'disclosure input hashes must be nonempty and unique'); END;
CREATE TRIGGER outbound_disclosures_input_hashes_nonempty_update BEFORE UPDATE OF selected_input_hashes ON outbound_disclosures WHEN json_array_length(NEW.selected_input_hashes)=0 OR EXISTS (SELECT value FROM json_each(NEW.selected_input_hashes) GROUP BY value HAVING count(*)>1) BEGIN SELECT RAISE(ABORT,'disclosure input hashes must be nonempty and unique'); END;
CREATE TRIGGER runner_registrations_revoked_immutable BEFORE UPDATE ON runner_registrations WHEN OLD.status='revoked' BEGIN SELECT RAISE(ABORT,'revoked runner registration is immutable'); END;
`

export const migrations: readonly Migration[] = [
  { id: "0001_core", sql: schemaSql },
  { id: "0002_provenance", sql: provenanceSql },
  { id: "0003_execution", sql: executionSql }
]

export const migrationChecksum = (migration: Migration): string =>
  createHash("sha256").update(migration.id).update("\0").update(migration.sql).digest("hex")
